# Generated by Django 4.1.7 on 2023-02-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmnotes",
            name="primary_key",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmregister",
            name="primary_key",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
