# Generated by Django 4.1.7 on 2023-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customadmin", "0002_farmnotes_primary_key_farmregister_primary_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmcrop",
            name="primary_key",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
