# Generated by Django 4.1.7 on 2023-02-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customadmin", "0004_remove_farmcrop_primary_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent_category_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent",
                to="customadmin.category",
            ),
        ),
    ]
