# Generated by Django 4.1.7 on 2023-02-27 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customadmin", "0005_category_parent_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent_category_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customadmin.category",
            ),
        ),
    ]
