# Generated by Django 4.1.7 on 2023-02-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customadmin", "0007_alter_category_parent_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmnotes",
            name="farm_crop_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customadmin.farmcrop"
            ),
        ),
        migrations.AlterField(
            model_name="farmregister",
            name="farm_crop_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customadmin.farmcrop"
            ),
        ),
    ]
