# Generated by Django 4.1.7 on 2023-02-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customadmin",
            "0009_remove_farmcrop_name_alter_farmnotes_farm_crop_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmregister",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
