# Generated by Django 4.1.7 on 2023-02-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customadmin", "0010_alter_farmregister_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmregister",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
