# Generated by Django 4.1.7 on 2023-03-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customadmin", "0012_alter_crop_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="parent_category_id",
            new_name="parent_category",
        ),
    ]
