# Generated by Django 4.1.7 on 2023-03-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customadmin", "0013_rename_parent_category_id_category_parent_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmcrop", name="status", field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name="farmregister", name="total_cost", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="farmregister", name="unit_acre", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="farmregister", name="unit_cost", field=models.IntegerField(),
        ),
    ]
