# Generated by Django 4.1.7 on 2023-03-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customadmin",
            "0014_alter_farmcrop_status_alter_farmregister_total_cost_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmcrop", name="planted_on", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="farmcrop",
            name="year_planted",
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="farmlease", name="date_from", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="farmlease", name="date_to", field=models.DateField(),
        ),
    ]
