# Generated by Django 4.1.5 on 2023-01-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_farm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="is_mine",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farm", name="size", field=models.BigIntegerField(null=True),
        ),
    ]
