# Generated by Django 4.1.5 on 2023-01-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_farm", "0003_crop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FarmRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_id", models.CharField(max_length=50)),
                ("unit_cost", models.CharField(max_length=50)),
                ("unit_acre", models.CharField(max_length=50)),
                ("total_cost", models.CharField(max_length=50)),
                ("quantity", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
