# Generated by Django 4.1.5 on 2023-01-19 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_farm", "0004_category_farmregister"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent_category_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base_farm.farmregister",
            ),
        ),
        migrations.AlterField(
            model_name="crop", name="duration", field=models.DurationField(),
        ),
    ]
