# Generated by Django 4.1.5 on 2023-01-26 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_farm", "0005_category_parent_category_id_alter_crop_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planted_on", models.DateTimeField(auto_now=True)),
                ("harvested_by", models.CharField(max_length=200)),
                ("year_planted", models.CharField(max_length=50)),
                ("status", models.TextField(blank=True)),
                (
                    "crop_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_farm.crop",
                    ),
                ),
                (
                    "farm_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_farm.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_id", models.CharField(max_length=20)),
                ("date_from", models.DateTimeField(auto_now_add=True)),
                ("date_to", models.DateTimeField(auto_now=True)),
                ("farmer_name", models.CharField(max_length=200)),
                ("farmer_phone", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FarmNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "farm_crop_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_farm.farmcrop",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="farm",
            name="farm_lease",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base_farm.farmlease",
            ),
        ),
    ]
