# Generated by Django 4.1.5 on 2023-01-26 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_farm", "0006_farmcrop_farmlease_farmnotes_farm_farm_lease"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="parent_category_id",),
        migrations.AlterField(
            model_name="farmregister",
            name="category_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base_farm.category",
            ),
        ),
    ]
